language: node_js

sudo: false

node_js:
  - '8'
  - '10'
  - '11'
  - '12'
  - 'stable'

install: yarn install

script:
  - yarn run lint
  - yarn run test

jobs:
  include:
  - stage: Produce Coverage
    node_js: node
    script: jest --coverage && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
